name: before_after
description: A flutter package which makes it easier to display the difference between two images.
version: 3.2.1

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"

topics:
  - slider
  - image-comparison
  - before-and-after
  - image-slider
  - image-compare

screenshots:
  - description: 'Package Demo'
    path: asset/package_demo.gif
